name: Velto
version: 0.3
main: com.aven0x.Velto.Velto
api-version: 1.21
commands:
  weather: {}
  sun: {}
  rain: {}
  thunder: {}
  spawn: {}
  setspawn: {}
  speed: {}
  kill: {}
  time: {}
  day: {}
  night: {}
  craft: {}
  anvil: {}
  gamemode: {}
  gms: {}
  gmc: {}
  gma: {}
  gmsp: {}
  feed: {}
  heal: {}
  broadcast: {}
  god: {}
  notiftest: {}
  list: {}
